/**
 * Database types. GENERATED by scripts/gen-db-types.mjs (same shape as
 * `supabase gen types typescript`). Don't edit by hand; regenerate after
 * adding a migration: DATABASE_URL=... npm run db:types
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      a2p_registrations: {
        Row: {
          org_id: string;
          status: string;
          brand_type: string;
          legal_name: string | null;
          ein: string | null;
          business_address: string | null;
          website: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          use_case_description: string | null;
          opt_in_description: string | null;
          sample_messages: Json;
          twilio_brand_sid: string | null;
          twilio_campaign_sid: string | null;
          admin_notes: string | null;
          submitted_at: string | null;
          decided_at: string | null;
          updated_at: string;
        };
        Insert: {
          org_id: string;
          status?: string;
          brand_type?: string;
          legal_name?: string | null;
          ein?: string | null;
          business_address?: string | null;
          website?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          use_case_description?: string | null;
          opt_in_description?: string | null;
          sample_messages?: Json;
          twilio_brand_sid?: string | null;
          twilio_campaign_sid?: string | null;
          admin_notes?: string | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          updated_at?: string;
        };
        Update: {
          org_id?: string;
          status?: string;
          brand_type?: string;
          legal_name?: string | null;
          ein?: string | null;
          business_address?: string | null;
          website?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          use_case_description?: string | null;
          opt_in_description?: string | null;
          sample_messages?: Json;
          twilio_brand_sid?: string | null;
          twilio_campaign_sid?: string | null;
          admin_notes?: string | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      calls: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string;
          lead_id: string | null;
          provider_sid: string | null;
          status: string;
          accepted: boolean;
          text_back_sent: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id: string;
          lead_id?: string | null;
          provider_sid?: string | null;
          status?: string;
          accepted?: boolean;
          text_back_sent?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string;
          lead_id?: string | null;
          provider_sid?: string | null;
          status?: string;
          accepted?: boolean;
          text_back_sent?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      consent_events: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string;
          kind: string;
          method: string;
          evidence: string | null;
          recorded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id: string;
          kind: string;
          method: string;
          evidence?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string;
          kind?: string;
          method?: string;
          evidence?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          org_id: string;
          phone: string;
          name: string | null;
          email: string | null;
          address: string | null;
          preferred_language: string;
          do_not_autotext: boolean;
          opted_out_at: string | null;
          marketing_consent_at: string | null;
          review_requested_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          phone: string;
          name?: string | null;
          email?: string | null;
          address?: string | null;
          preferred_language?: string;
          do_not_autotext?: boolean;
          opted_out_at?: string | null;
          marketing_consent_at?: string | null;
          review_requested_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          phone?: string;
          name?: string | null;
          email?: string | null;
          address?: string | null;
          preferred_language?: string;
          do_not_autotext?: boolean;
          opted_out_at?: string | null;
          marketing_consent_at?: string | null;
          review_requested_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          org_id: string;
          token: string;
          role: string;
          created_by: string;
          expires_at: string;
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          token?: string;
          role?: string;
          created_by?: string;
          expires_at?: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          token?: string;
          role?: string;
          created_by?: string;
          expires_at?: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string;
          stage: string;
          source: string;
          broadcast_id: string | null;
          estimate_amount_cents: number | null;
          notes: string | null;
          flag: string | null;
          unread: boolean;
          last_message_at: string;
          first_response_at: string | null;
          stage_changed_at: string;
          estimate_sent_at: string | null;
          won_at: string | null;
          lost_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id: string;
          stage?: string;
          source?: string;
          broadcast_id?: string | null;
          estimate_amount_cents?: number | null;
          notes?: string | null;
          flag?: string | null;
          unread?: boolean;
          last_message_at?: string;
          first_response_at?: string | null;
          stage_changed_at?: string;
          estimate_sent_at?: string | null;
          won_at?: string | null;
          lost_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string;
          stage?: string;
          source?: string;
          broadcast_id?: string | null;
          estimate_amount_cents?: number | null;
          notes?: string | null;
          flag?: string | null;
          unread?: boolean;
          last_message_at?: string;
          first_response_at?: string | null;
          stage_changed_at?: string;
          estimate_sent_at?: string | null;
          won_at?: string | null;
          lost_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          org_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          org_id: string;
          user_id: string;
          role: string;
          created_at?: string;
        };
        Update: {
          org_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      message_templates: {
        Row: {
          id: string;
          org_id: string;
          key: string;
          language: string;
          category: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          key: string;
          language: string;
          category: string;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          key?: string;
          language?: string;
          category?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string;
          lead_id: string | null;
          direction: string;
          body: string;
          category: string | null;
          sender_type: string;
          sent_by: string | null;
          provider_sid: string | null;
          status: string;
          error: string | null;
          flag: string | null;
          broadcast_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id: string;
          lead_id?: string | null;
          direction: string;
          body: string;
          category?: string | null;
          sender_type: string;
          sent_by?: string | null;
          provider_sid?: string | null;
          status: string;
          error?: string | null;
          flag?: string | null;
          broadcast_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string;
          lead_id?: string | null;
          direction?: string;
          body?: string;
          category?: string | null;
          sender_type?: string;
          sent_by?: string | null;
          provider_sid?: string | null;
          status?: string;
          error?: string | null;
          flag?: string | null;
          broadcast_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          org_id: string;
          kind: string;
          body: string;
          link: string | null;
          sms_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          kind: string;
          body: string;
          link?: string | null;
          sms_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          kind?: string;
          body?: string;
          link?: string | null;
          sms_status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          business_type: string;
          timezone: string;
          default_language: string;
          alert_phone: string | null;
          google_review_url: string | null;
          settings: Json;
          plan_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          business_type: string;
          timezone?: string;
          default_language?: string;
          alert_phone?: string | null;
          google_review_url?: string | null;
          settings?: Json;
          plan_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          business_type?: string;
          timezone?: string;
          default_language?: string;
          alert_phone?: string | null;
          google_review_url?: string | null;
          settings?: Json;
          plan_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      phone_numbers: {
        Row: {
          id: string;
          org_id: string;
          e164: string;
          provider: string;
          provider_sid: string | null;
          messaging_service_sid: string | null;
          setup_mode: string;
          forward_to: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          e164: string;
          provider?: string;
          provider_sid?: string | null;
          messaging_service_sid?: string | null;
          setup_mode?: string;
          forward_to?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          e164?: string;
          provider?: string;
          provider_sid?: string | null;
          messaging_service_sid?: string | null;
          setup_mode?: string;
          forward_to?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          monthly_price_cents: number;
          stripe_price_id: string | null;
          max_users: number;
          max_phone_numbers: number;
          monthly_sms_limit: number;
          feature_recurring_customers: boolean;
          feature_bulk_messaging: boolean;
          feature_campaigns: boolean;
          is_public: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          monthly_price_cents?: number;
          stripe_price_id?: string | null;
          max_users: number;
          max_phone_numbers: number;
          monthly_sms_limit: number;
          feature_recurring_customers?: boolean;
          feature_bulk_messaging?: boolean;
          feature_campaigns?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          monthly_price_cents?: number;
          stripe_price_id?: string | null;
          max_users?: number;
          max_phone_numbers?: number;
          monthly_sms_limit?: number;
          feature_recurring_customers?: boolean;
          feature_bulk_messaging?: boolean;
          feature_campaigns?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          org_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          status: string;
          current_period_end: string | null;
          updated_at: string;
        };
        Insert: {
          org_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_end?: string | null;
          updated_at?: string;
        };
        Update: {
          org_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_end?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      usage_counters: {
        Row: {
          org_id: string;
          month: string;
          sms_sent: number;
        };
        Insert: {
          org_id: string;
          month: string;
          sms_sent?: number;
        };
        Update: {
          org_id?: string;
          month?: string;
          sms_sent?: number;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_invitation: { Args: { p_token: string }; Returns: string };
      create_organization: { Args: { p_name: string; p_business_type: string; p_default_language: string; p_templates: Json; p_alert_phone?: string; p_google_review_url?: string }; Returns: string };
      get_invitation: { Args: { p_token: string }; Returns: { org_name: string; role: string; is_valid: boolean }[] };
      has_org_role: { Args: { p_org_id: string; p_role: string }; Returns: boolean };
      increment_sms_usage: { Args: { p_org_id: string; p_month: string; p_count?: number }; Returns: number };
      is_org_member: { Args: { p_org_id: string }; Returns: boolean };
      record_consent_event: { Args: { p_org_id: string; p_contact_id: string; p_kind: string; p_method: string; p_evidence?: string }; Returns: undefined };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
